onEvent('recipes', evt => {
    const removeCrafting = {
        create: [
            'cogwheel',
            'large_cogwheel',
            'mechanical_piston',
            'sticky_mechanical_piston',
            'piston_extension_pole',
            'gantry_carriage',
            'gantry_shaft',
            'windmill_bearing',
            'mechanical_bearing',
            'rope_pulley',
            'cart_assembler',
            'gearbox',
            'vertical_gearbox',
            'clutch',
            'gearshift',
            'encased_chain_drive',
            'adjustable_chain_gearshift',
            'water_wheel',
            'encased_fan',
            'nozzle',
            'windmill_bearing',
            'mechanical_bearing',
            'clockwork_bearing',
            'rope_pulley',
            'cart_assembler',
            'linear_chassis',
            'secondary_linear_chassis',
            'radial_chassis',
            'sticker',
            'mysterious_cuckoo_clock',
            'mechanical_press',
            'mechanical_mixer',
            'fluid_pipe',
            'mechanical_pump',
            'smart_fluid_pipe',
            'fluid_valve',
            'copper_valve_handle',
            'millstone',
            'mechanical_press',
            'basin',
            'empty_blaze_burner',
            'depot',
            'weighted_ejector',
            'cuckoo_clock',
            'andesite_alloy',
            'mechanical_arm',
            'rotation_speed_controller',
            'mechanical_plough',
            'mechanical_harvester',
            'redstone_contact',
            'portable_storage_interface',
            'deployer',
            'mechanical_saw',
            'mechanical_drill',
            'item_drain',
            'hose_pulley',
            'fluid_tank',
            'schematic_table',
            'schematicannon',
            'powered_toggle_latch',
            'powered_latch',
            'pulse_extender',
            'pulse_repeater',
            'placard',
            'analog_lever',
            'nixie_tube',
            'redstone_link',
            'display_board',
            'display_link',
            'stockpile_switch',
            'content_observer',
            'brass_tunnel',
            'brass_funnel',
            'controls',
            'andesite_funnel',
            'track_observer',
            'track_signal',
            'track_station',
            'nixie_tube',
            'schedule',
            'track',

        ]
    }

    let mods = Object.keys(removeCrafting)
    mods.forEach(mod => {
        let items = removeCrafting[mod]
        items.forEach(item => {
            //evt.remove({ output: "create:" + item })
        })
    })
})